name: publish to nuget
on:
  push:
    branches:
      - master # Your default release branch
jobs:
  publish:
    name: publish to nuget
    runs-on: ubuntu-latest
    steps:
      # Checkout
      - uses: actions/checkout@v2

      # Optional step, add only for a specific dotnet version that doesn't come with ubuntu-latest / windows-latest
      # Visit bit.ly/2synnZl for a list of software that comes pre-installed with ubuntu-latest / windows-latest
#       - name: Setup dotnet
#         uses: actions/setup-dotnet@v1
#         with:
#            dotnet-version: 3.1.100
      
      # Publish
      - name: Publish if version is updated
        uses: rohith/publish-nuget@v1.2.0
        with: # All inputs are optional (details given below)
          nuget_key: ${{secrets.NUGET_API_KEY}} # nuget.org API key
        #   project_dir: src # Defaults to repository root
        #   tag_format: v* # [*] gets replaced with version
            
